version: "3.7"
services:

  producer:
    build:
      context: .
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    #networks:
    #  - kafka_network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

#networks:
#  kafka_network:
#    external: true

volumes:
  dbdata:
    driver: local
    labels:
      mf.project.name: kafka-first-steps-producer